export type LeadType = "cold" | "warm";
export type LeadStatus = "closed" | "lost";
export type LeadSource =
  | "linkedin"
  | "google"
  | "referral"
  | "website"
  | "cold-call";

export interface Lead {
  id: string;
  name: string;
  avatar: string;
  type: LeadType;
  email: string;
  followUp: string;
  status: LeadStatus;
  website: string;
  score: number;
  source: LeadSource;
}

export interface TopPerformer {
  id: string;
  name: string;
  avatar: string;
  score: number;
  icon: "star" | "user";
}

export const dashboardStats = {
  generatedRevenue: {
    value: "$67,024",
    change: 12,
  },
  signedClients: {
    value: "227",
    change: 23,
  },
  totalLeads: {
    value: "3,867",
    change: 17,
  },
  teamMembers: {
    value: "38",
    activeCount: 6,
  },
};

export const leadsChartDataWeek = [
  { date: "Mon", line1: 180, line2: 220, line3: 280, line4: 350 },
  { date: "Tue", line1: 420, line2: 550, line3: 380, line4: 280 },
  { date: "Wed", line1: 280, line2: 380, line3: 520, line4: 450 },
  { date: "Thu", line1: 550, line2: 280, line3: 420, line4: 620 },
  { date: "Fri", line1: 323, line2: 729, line3: 506, line4: 490 },
  { date: "Sat", line1: 480, line2: 420, line3: 280, line4: 380 },
  { date: "Sun", line1: 220, line2: 550, line3: 450, line4: 320 },
];

export const leadsChartDataMonth = [
  { date: "Jan 1", line1: 180, line2: 220, line3: 280, line4: 350 },
  { date: "Jan 5", line1: 420, line2: 550, line3: 380, line4: 280 },
  { date: "Jan 9", line1: 280, line2: 380, line3: 520, line4: 450 },
  { date: "Jan 13", line1: 550, line2: 280, line3: 420, line4: 620 },
  { date: "Jan 15", line1: 323, line2: 729, line3: 506, line4: 490 },
  { date: "Jan 17", line1: 480, line2: 420, line3: 280, line4: 380 },
  { date: "Jan 21", line1: 220, line2: 550, line3: 450, line4: 320 },
  { date: "Jan 25", line1: 380, line2: 320, line3: 580, line4: 480 },
  { date: "Jan 30", line1: 520, line2: 450, line3: 350, line4: 420 },
];

export const leadsChartDataQuarter = [
  { date: "Jan", line1: 320, line2: 450, line3: 380, line4: 420 },
  { date: "Feb", line1: 480, line2: 380, line3: 520, line4: 350 },
  { date: "Mar", line1: 550, line2: 620, line3: 450, line4: 580 },
  { date: "Apr", line1: 420, line2: 510, line3: 380, line4: 490 },
  { date: "May", line1: 380, line2: 450, line3: 620, line4: 420 },
  { date: "Jun", line1: 620, line2: 380, line3: 510, line4: 550 },
  { date: "Jul", line1: 520, line2: 580, line3: 450, line4: 480 },
  { date: "Aug", line1: 450, line2: 490, line3: 380, line4: 620 },
  { date: "Sep", line1: 580, line2: 420, line3: 550, line4: 380 },
];

export const topPerformers: TopPerformer[] = [
  {
    id: "1",
    name: "Sarah M.",
    avatar: "https://api.dicebear.com/9.x/icons/svg?seed=sarah",
    score: 120,
    icon: "star",
  },
  {
    id: "2",
    name: "James K.",
    avatar: "https://api.dicebear.com/9.x/icons/svg?seed=james",
    score: 60,
    icon: "user",
  },
  {
    id: "3",
    name: "Emily R.",
    avatar: "https://api.dicebear.com/9.x/icons/svg?seed=emily",
    score: 21,
    icon: "user",
  },
  {
    id: "4",
    name: "Michael L.",
    avatar: "https://api.dicebear.com/9.x/icons/svg?seed=michael",
    score: 3,
    icon: "user",
  },
  {
    id: "5",
    name: "Alex T.",
    avatar: "https://api.dicebear.com/9.x/icons/svg?seed=alex",
    score: 45,
    icon: "user",
  },
];

export const leads: Lead[] = [
  {
    id: "1",
    name: "Sarah",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sarah",
    type: "cold",
    email: "sarah@brightwave.co",
    followUp: "In 1 day",
    status: "closed",
    website: "brightwave.co",
    score: 87,
    source: "linkedin",
  },
  {
    id: "2",
    name: "James",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=james",
    type: "warm",
    email: "james@gmail.com",
    followUp: "In 1 day",
    status: "lost",
    website: "-",
    score: 42,
    source: "google",
  },
  {
    id: "3",
    name: "Daniela",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=daniela",
    type: "cold",
    email: "daniela@avella.io",
    followUp: "In 2 days",
    status: "lost",
    website: "avella.io",
    score: 65,
    source: "referral",
  },
  {
    id: "4",
    name: "Lucas",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=lucas",
    type: "cold",
    email: "lucas@yahoo.com",
    followUp: "In 3 days",
    status: "lost",
    website: "-",
    score: 28,
    source: "cold-call",
  },
  {
    id: "5",
    name: "Emily",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=emily",
    type: "warm",
    email: "emily@zencloud.com",
    followUp: "In 1 week",
    status: "closed",
    website: "zencloud.com",
    score: 94,
    source: "website",
  },
  {
    id: "6",
    name: "Priya",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=priya",
    type: "warm",
    email: "priya@auroratech.io",
    followUp: "In 1 week",
    status: "lost",
    website: "auroratech.io",
    score: 73,
    source: "linkedin",
  },
  {
    id: "7",
    name: "Michael",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=michael",
    type: "cold",
    email: "michael@outlook.com",
    followUp: "In 2 weeks",
    status: "closed",
    website: "brightwave.co",
    score: 56,
    source: "referral",
  },
  {
    id: "8",
    name: "Olivia",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=olivia",
    type: "warm",
    email: "olivia@nextera.io",
    followUp: "In 3 days",
    status: "closed",
    website: "nextera.io",
    score: 91,
    source: "linkedin",
  },
  {
    id: "9",
    name: "Noah",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=noah",
    type: "cold",
    email: "noah@techflow.com",
    followUp: "In 1 day",
    status: "lost",
    website: "techflow.com",
    score: 35,
    source: "google",
  },
  {
    id: "10",
    name: "Sophia",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sophia",
    type: "warm",
    email: "sophia@cloudbase.io",
    followUp: "In 2 days",
    status: "closed",
    website: "cloudbase.io",
    score: 82,
    source: "website",
  },
  {
    id: "11",
    name: "Liam",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=liam",
    type: "cold",
    email: "liam@datastream.co",
    followUp: "In 1 week",
    status: "lost",
    website: "datastream.co",
    score: 47,
    source: "cold-call",
  },
  {
    id: "12",
    name: "Ava",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ava",
    type: "warm",
    email: "ava@synthwave.io",
    followUp: "In 3 days",
    status: "closed",
    website: "synthwave.io",
    score: 88,
    source: "referral",
  },
  {
    id: "13",
    name: "Ethan",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ethan",
    type: "cold",
    email: "ethan@gmail.com",
    followUp: "In 2 weeks",
    status: "lost",
    website: "-",
    score: 22,
    source: "google",
  },
  {
    id: "14",
    name: "Isabella",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=isabella",
    type: "warm",
    email: "isabella@pixelforge.com",
    followUp: "In 1 day",
    status: "closed",
    website: "pixelforge.com",
    score: 96,
    source: "linkedin",
  },
  {
    id: "15",
    name: "Mason",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=mason",
    type: "cold",
    email: "mason@outlook.com",
    followUp: "In 4 days",
    status: "lost",
    website: "-",
    score: 38,
    source: "cold-call",
  },
  {
    id: "16",
    name: "Mia",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=mia",
    type: "warm",
    email: "mia@vortexlabs.io",
    followUp: "In 2 days",
    status: "closed",
    website: "vortexlabs.io",
    score: 79,
    source: "website",
  },
  {
    id: "17",
    name: "Alexander",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=alexander",
    type: "cold",
    email: "alex@fusiontech.co",
    followUp: "In 1 week",
    status: "lost",
    website: "fusiontech.co",
    score: 51,
    source: "referral",
  },
  {
    id: "18",
    name: "Charlotte",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=charlotte",
    type: "warm",
    email: "charlotte@novawave.io",
    followUp: "In 3 days",
    status: "closed",
    website: "novawave.io",
    score: 84,
    source: "linkedin",
  },
  {
    id: "19",
    name: "Benjamin",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=benjamin",
    type: "cold",
    email: "ben@yahoo.com",
    followUp: "In 5 days",
    status: "lost",
    website: "-",
    score: 31,
    source: "google",
  },
  {
    id: "20",
    name: "Amelia",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=amelia",
    type: "warm",
    email: "amelia@quantumleap.io",
    followUp: "In 1 day",
    status: "closed",
    website: "quantumleap.io",
    score: 92,
    source: "website",
  },
  {
    id: "21",
    name: "William",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=william",
    type: "cold",
    email: "william@cybercore.com",
    followUp: "In 2 weeks",
    status: "lost",
    website: "cybercore.com",
    score: 44,
    source: "cold-call",
  },
  {
    id: "22",
    name: "Harper",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=harper",
    type: "warm",
    email: "harper@stellartech.io",
    followUp: "In 2 days",
    status: "closed",
    website: "stellartech.io",
    score: 77,
    source: "referral",
  },
  {
    id: "23",
    name: "Jacob",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=jacob",
    type: "cold",
    email: "jacob@netpulse.co",
    followUp: "In 4 days",
    status: "lost",
    website: "netpulse.co",
    score: 59,
    source: "linkedin",
  },
  {
    id: "24",
    name: "Evelyn",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=evelyn",
    type: "warm",
    email: "evelyn@gmail.com",
    followUp: "In 1 week",
    status: "closed",
    website: "-",
    score: 68,
    source: "google",
  },
  {
    id: "25",
    name: "Daniel",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=daniel",
    type: "cold",
    email: "daniel@infracloud.io",
    followUp: "In 3 days",
    status: "lost",
    website: "infracloud.io",
    score: 41,
    source: "website",
  },
  {
    id: "26",
    name: "Abigail",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=abigail",
    type: "warm",
    email: "abigail@hyperloop.co",
    followUp: "In 1 day",
    status: "closed",
    website: "hyperloop.co",
    score: 89,
    source: "linkedin",
  },
  {
    id: "27",
    name: "Henry",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=henry",
    type: "cold",
    email: "henry@outlook.com",
    followUp: "In 6 days",
    status: "lost",
    website: "-",
    score: 26,
    source: "cold-call",
  },
  {
    id: "28",
    name: "Elizabeth",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=elizabeth",
    type: "warm",
    email: "elizabeth@neurolink.io",
    followUp: "In 2 days",
    status: "closed",
    website: "neurolink.io",
    score: 95,
    source: "referral",
  },
  {
    id: "29",
    name: "Sebastian",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sebastian",
    type: "cold",
    email: "sebastian@codecraft.com",
    followUp: "In 1 week",
    status: "lost",
    website: "codecraft.com",
    score: 53,
    source: "google",
  },
  {
    id: "30",
    name: "Sofia",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sofia",
    type: "warm",
    email: "sofia@blueshift.io",
    followUp: "In 3 days",
    status: "closed",
    website: "blueshift.io",
    score: 81,
    source: "website",
  },
  {
    id: "31",
    name: "Jack",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=jack",
    type: "cold",
    email: "jack@dynamix.co",
    followUp: "In 4 days",
    status: "lost",
    website: "dynamix.co",
    score: 37,
    source: "linkedin",
  },
  {
    id: "32",
    name: "Ella",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ella",
    type: "warm",
    email: "ella@prismtech.io",
    followUp: "In 1 day",
    status: "closed",
    website: "prismtech.io",
    score: 86,
    source: "referral",
  },
  {
    id: "33",
    name: "Owen",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=owen",
    type: "cold",
    email: "owen@gmail.com",
    followUp: "In 2 weeks",
    status: "lost",
    website: "-",
    score: 29,
    source: "cold-call",
  },
  {
    id: "34",
    name: "Victoria",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=victoria",
    type: "warm",
    email: "victoria@echosys.com",
    followUp: "In 2 days",
    status: "closed",
    website: "echosys.com",
    score: 93,
    source: "google",
  },
  {
    id: "35",
    name: "Samuel",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=samuel",
    type: "cold",
    email: "samuel@gridlock.io",
    followUp: "In 5 days",
    status: "lost",
    website: "gridlock.io",
    score: 48,
    source: "website",
  },
  {
    id: "36",
    name: "Grace",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=grace",
    type: "warm",
    email: "grace@zenithlab.co",
    followUp: "In 3 days",
    status: "closed",
    website: "zenithlab.co",
    score: 76,
    source: "linkedin",
  },
  {
    id: "37",
    name: "Joseph",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=joseph",
    type: "cold",
    email: "joseph@yahoo.com",
    followUp: "In 1 week",
    status: "lost",
    website: "-",
    score: 33,
    source: "referral",
  },
  {
    id: "38",
    name: "Chloe",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=chloe",
    type: "warm",
    email: "chloe@pulsewave.io",
    followUp: "In 1 day",
    status: "closed",
    website: "pulsewave.io",
    score: 90,
    source: "cold-call",
  },
  {
    id: "39",
    name: "David",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=david",
    type: "cold",
    email: "david@nexgen.com",
    followUp: "In 4 days",
    status: "lost",
    website: "nexgen.com",
    score: 55,
    source: "google",
  },
  {
    id: "40",
    name: "Zoey",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=zoey",
    type: "warm",
    email: "zoey@sparkline.io",
    followUp: "In 2 days",
    status: "closed",
    website: "sparkline.io",
    score: 83,
    source: "website",
  },
  {
    id: "41",
    name: "Carter",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=carter",
    type: "cold",
    email: "carter@outlook.com",
    followUp: "In 6 days",
    status: "lost",
    website: "-",
    score: 24,
    source: "linkedin",
  },
  {
    id: "42",
    name: "Lily",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=lily",
    type: "warm",
    email: "lily@orbittech.co",
    followUp: "In 3 days",
    status: "closed",
    website: "orbittech.co",
    score: 97,
    source: "referral",
  },
  {
    id: "43",
    name: "Wyatt",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=wyatt",
    type: "cold",
    email: "wyatt@flowstate.io",
    followUp: "In 1 week",
    status: "lost",
    website: "flowstate.io",
    score: 46,
    source: "cold-call",
  },
  {
    id: "44",
    name: "Hannah",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=hannah",
    type: "warm",
    email: "hannah@skyvault.com",
    followUp: "In 1 day",
    status: "closed",
    website: "skyvault.com",
    score: 85,
    source: "google",
  },
  {
    id: "45",
    name: "Gabriel",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=gabriel",
    type: "cold",
    email: "gabriel@gmail.com",
    followUp: "In 5 days",
    status: "lost",
    website: "-",
    score: 39,
    source: "website",
  },
  {
    id: "46",
    name: "Aria",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=aria",
    type: "warm",
    email: "aria@chronotech.io",
    followUp: "In 2 days",
    status: "closed",
    website: "chronotech.io",
    score: 78,
    source: "linkedin",
  },
  {
    id: "47",
    name: "Julian",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=julian",
    type: "cold",
    email: "julian@vertexai.co",
    followUp: "In 2 weeks",
    status: "lost",
    website: "vertexai.co",
    score: 52,
    source: "referral",
  },
  {
    id: "48",
    name: "Penelope",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=penelope",
    type: "warm",
    email: "penelope@luminex.io",
    followUp: "In 3 days",
    status: "closed",
    website: "luminex.io",
    score: 99,
    source: "cold-call",
  },
  {
    id: "49",
    name: "Levi",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=levi",
    type: "cold",
    email: "levi@yahoo.com",
    followUp: "In 4 days",
    status: "lost",
    website: "-",
    score: 32,
    source: "google",
  },
  {
    id: "50",
    name: "Layla",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=layla",
    type: "warm",
    email: "layla@radiantlab.com",
    followUp: "In 1 day",
    status: "closed",
    website: "radiantlab.com",
    score: 88,
    source: "website",
  },
];

export const sidebarNavItems = [
  { title: "Search", icon: "search", shortcut: "/" },
  { title: "Inbox", icon: "inbox" },
  { title: "Dashboard", icon: "analytics", isActive: true },
  { title: "My Tasks", icon: "tasks" },
  { title: "Projects", icon: "layers" },
  { title: "Calendar", icon: "calendar" },
  { title: "Documents", icon: "file" },
  { title: "Teams", icon: "users" },
  { title: "Company", icon: "building" },
];

export const workgroups = [
  {
    id: "all-work",
    name: "All Work",
    icon: "globe",
    children: [
      {
        id: "website-copy",
        name: "Website Copy",
        icon: "folder",
        children: [
          { id: "client-website", name: "Client website", icon: "file" },
          { id: "personal-project", name: "Personal project", icon: "file" },
        ],
      },
      { id: "ux-research", name: "UX Research", icon: "folder" },
      { id: "assets-library", name: "Assets Library", icon: "folder" },
    ],
  },
  { id: "marketing", name: "Marketing", icon: "megaphone" },
  { id: "development", name: "Development", icon: "code" },
  { id: "support", name: "Support", icon: "headphones" },
];